# Generated by Django 5.2.7 on 2025-10-24 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField(default=0)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_urls', models.TextField(blank=True, help_text='Masukkan satu URL gambar per baris.', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_link', models.URLField(max_length=1024)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
